# Generated by Django 6.0.1 on 2026-01-10 15:07

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Products', 'Products'), ('Dishes', 'Dishes'), ('Drinks', 'Drinks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-2), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'item')},
        ),
    ]
