# Generated by Django 6.0.1 on 2026-01-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rating_created_at_alter_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('products', 'products'), ('dishes', 'dishes'), ('drinks', 'drinks')], max_length=20),
        ),
    ]
