# Generated by Django 6.0.1 on 2026-01-11 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
