# Generated by Django 6.0.1 on 2026-01-11 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_statsshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='statsshare',
            name='snapshot_hash',
            field=models.CharField(db_index=True, default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='statsshare',
            unique_together={('user', 'category', 'snapshot_hash')},
        ),
    ]
