# Generated by Django 6.0.1 on 2026-01-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_statsshare_snapshot_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/6/65/No-Image-Placeholder.svg', null=True),
        ),
    ]
