# Generated by Django 6.0.1 on 2026-01-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='no-image-available.svg', null=True, upload_to='items/'),
        ),
    ]
